# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Rx-chapter-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rx-chapter-2
  pod 'RxSwift', '~> 4.0'
end
